POST http://192.168.39.54:30850
Content-Type: application/cloudevents+json

{
  "specversion": "1.0",
  "type": "stuff.demo",
  "source": "inbound-a",
  "id": "2",
  "datacontenttype": "application/json",
  "data": "{\"data\":2}"
}

###

POST http://192.168.39.54:32615
Content-Type: application/cloudevents+json

{
  "specversion": "1.0",
  "type": "number.demo",
  "source": "inbound-b",
  "id": "2",
  "datacontenttype": "application/json",
  "data": "{\"data\":3}"
}

###
