apiVersion: v1
kind: Service
metadata:
  name: inbound-a
spec:
  selector:
    inbound: a
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: inbound-a
  labels:
    inbound: a
spec:
  containers:
    - name: inbound
      image: docker.io/slinkydeveloper/inbound
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: NAME # Stream name
          value: inbound-a
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"

---

apiVersion: v1
kind: Service
metadata:
  name: inbound-b
spec:
  selector:
    inbound: b
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: inbound-b
  labels:
    inbound: b
spec:
  containers:
    - name: inbound
      image: docker.io/slinkydeveloper/inbound
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: NAME # Stream name
          value: inbound-b
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"

---

apiVersion: v1
kind: Pod
metadata:
  name: join
spec:
  volumes:
    - name: uds-data
      emptyDir: {}
  containers:
    - name: join-function
      image: docker.io/slinkydeveloper/demo-join-function
      imagePullPolicy: Never
      volumeMounts:
        - name: uds-data
          mountPath: /data
    - name: join-runtime
      image: docker.io/slinkydeveloper/join
      imagePullPolicy: Never
      volumeMounts:
        - name: uds-data
          mountPath: /data
      env:
        - name: LEFT_STREAM
          value: inbound-a
        - name: RIGHT_STREAM
          value: inbound-b
        - name: SUCCESS_STREAM
          value: outbound
        - name: WINDOW_LENGTH
          value: "PT5M"
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"



