POST http://192.168.39.47:31694
Content-Type: application/cloudevents+json

{
  "specversion" : "1.0",
  "type" : "number.demo",
  "source" : "inbound-a",
  "id" : "3",
  "datacontenttype" : "text/plain",
  "data" : "-10"
}

###

POST http://192.168.39.47:31057
Content-Type: application/cloudevents+json

{
  "specversion" : "1.0",
  "type" : "number.demo",
  "source" : "inbound-b",
  "id" : "2",
  "datacontenttype" : "text/plain",
  "data" : "-20"
}

###
