apiVersion: v1
kind: Service
metadata:
  name: inbound-stocks
spec:
  selector:
    inbound: stocks
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: inbound-stocks
  labels:
    inbound: stocks
spec:
  containers:
    - name: inbound
      image: docker.io/slinkydeveloper/inbound-kafka
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: NAME # Stream name
          value: inbound-stocks
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
