apiVersion: streaming.knative.dev/v1alpha1
kind: StreamProcessor
metadata:
  name: stocks-filter
spec:
  input:
    - name: inbound-stocks
      parameterName: input
      key: id
  output:
    - name: filtered-stocks
      parameterName: output
      key: stockname
  container:
    name: demo-stocks-filter
    image: docker.io/slinkydeveloper/demo-stocks-filter
    env:
      - name: FAAS_LOG
        value: "true"
      - name: STOCKS
        value: "rht,ibm"

---

apiVersion: streaming.knative.dev/v1alpha1
kind: StreamProcessor
metadata:
  name: stocks-decisions
spec:
  input:
    - name: filtered-stocks
      parameterName: "input"
  output:
    - name: decisions
      parameterName: "output"
  state:
    name: state-stocks
    parameterName: state
    key: stockname
  container:
    name: demo-stocks-decisions
    image: docker.io/slinkydeveloper/demo-stocks-decisions
    env:
      - name: FAAS_LOG
        value: "true"
      - name: BUY_THRESHOLD
        value: "0.05"
      - name: SELL_THRESHOLD
        value: "-0.05"

---

apiVersion: streaming.knative.dev/v1alpha1
kind: StreamProcessor
metadata:
  name: stocks-decisions-logger
spec:
  input:
    - name: decisions
      parameterName: input
  container:
    name: demo-stocks-decisions-logger
    image: docker.io/slinkydeveloper/demo-stocks-decisions-logger
    env:
      - name: FAAS_LOG
        value: "true"
