apiVersion: streaming.knative.dev/v1alpha1
kind: StreamProcessor
metadata:
  name: joiner
spec:
  input:
    - name: inbound-a
      parameterName: "x"
    - name: inbound-b
      parameterName: "y"
  output:
    - name: positive
    - name: negative
  container:
    name: sum
    image: docker.io/slinkydeveloper/demo-join-function
    imagePullPolicy: Never
    env:
      - name: FAAS_LOG
        value: "true"

---

apiVersion: streaming.knative.dev/v1alpha1
kind: StreamProcessor
metadata:
  name: logger-positive
spec:
  input:
    - name: positive
      parameterName: "input"
  container:
    name: logger-function
    image: docker.io/slinkydeveloper/demo-logger
    imagePullPolicy: Never
    env:
      - name: FAAS_LOG
        value: "true"

---

apiVersion: streaming.knative.dev/v1alpha1
kind: StreamProcessor
metadata:
  name: logger-negative
spec:
  input:
    - name: negative
      parameterName: "input"
  container:
    name: logger-function
    image: docker.io/slinkydeveloper/demo-logger
    imagePullPolicy: Never
    env:
      - name: FAAS_LOG
        value: "true"
